### ISSUE TITLE
OJEU records added to the search

### ISSUE THREAD

**Issue by davidread** [datagovuk/contracts-archive#10]
Have the record or link to the OJEU

**Comment by morty** [comment]
If we can filter out the non-UK records I think it would be easiest to import them all in the same way as the records we already have.

It might also be useful to link to the record on http://ted.europa.eu

**Comment by davidread** [comment]
We should check analytics for the page to see if it is used

**Comment by morty** [comment]
We think that we already have all of the OJEU notices on the site.
