### ISSUE TITLE
Add filtering

### ISSUE THREAD

**Issue by morty** [datagovuk/contracts-archive#27]
Possible filters

* Award notice? (Asked for by Adam)
* Location
* Supplier
* Purchasing Department
* Value
* OJEU notice?
* Tender date
* Award date
* CPV (would need to import this data)

**Comment by davidread** [comment]
Aiming to base design on:

Civil Service Jobs:
https://www.civilservicejobs.service.gov.uk/csr/index.cgi?SID=cGFnZWFjdGlvbj1zZWFyY2hieWNvbnRleHRpZCZ1c2Vyc2VhcmNoY29udGV4dD05Nzc3MTI3JnBhZ2VjbGFzcz1Kb2JzJmtleT1mYWly

GDS contracts finder:
https://www.contractsfinder.service.gov.uk/Search/Results?LocationType=AllLocations&ValueFrom=1000000

**Comment by davidread** [comment]
Demo at: https://test.data.gov.uk/data/contracts-finder-archive/search/?q=

**Comment by morty** [comment]
I've changed the default sort order to be by publication date (which doesn't have the same issue with outliers as the other two dates).

When ordering by deadline date or award date an extra column is shown so that you can see how the ordering is working.

I am recreating the index which takes a while now. Can deploy once this has finished.

**Comment by davidread** [comment]
Work done on this branch: https://github.com/datagovuk/contracts-archive/commits/facet-search

**Comment by davidread** [comment]
Do deploy

**Comment by morty** [comment]
Deployed to live and seems to be working well.

**Comment by davidread** [comment]
Nice one, I've added a blog post for it: https://data.gov.uk/blog/improved-search-contracts-finder-archive too and linked from the home page
