### ISSUE TITLE
Say that OJEU is not there (yet)

### ISSUE THREAD

**Issue by davidread** [datagovuk/contracts-archive#9]
Along the lines of 'OJEU notices can be found on TED for the time being'

**Comment by davidread** [comment]
My understanding is different - that OJEU publishes contracts OVER a certain threshold, and that we have excluded those from search and listings, but they are available in the data downloads. Can you confirm? And let's say what the value of the OJEU threshold is.

**Comment by morty** [comment]
Good spot. Of course it should say that we **do not** have records over the OJEU threshold.

I don't think the threshold is a single number. I'm looking for a good page to reference.
